In [4]:

import pandas as pd
import numpy as np

In [5]:

listings = pd.read_csv("../data/raw/listings.csv.gz")
calendar = pd.read_csv("../data/raw/calendar.csv.gz")
reviews = pd.read_csv("../data/raw/reviews.csv.gz")
neighbourhoods = pd.read_csv("../data/raw/neighbourhoods.csv")

In [6]:
listings.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,13913,https://www.airbnb.com/rooms/13913,20250914034649,2025-09-16,city scrape,Holiday London DB Room Let-on going,My bright double bedroom with a large window h...,Finsbury Park is a friendly melting pot commun...,https://a0.muscache.com/pictures/miso/Hosting-...,54730,...,4.87,4.78,4.78,NaN,f,2,1,1,0,0.30
1,15400,https://www.airbnb.com/rooms/15400,20250914034649,2025-09-16,city scrape,Bright Chelsea Apartment. Chelsea!,Lots of windows and light. St Luke's Gardens ...,It is Chelsea.,https://a0.muscache.com/pictures/428392/462d26...,60302,...,4.84,4.93,4.74,NaN,f,1,1,0,0,0.51
2,17402,https://www.airbnb.com/rooms/17402,20250914034649,2025-09-16,city scrape,Very Central Modern 3-Bed/2 Bath By Oxford St W1,"You'll have a great time in this beautiful, cl...","Fitzrovia is a very desirable trendy, arty and...",https://a0.muscache.com/pictures/39d5309d-fba7...,67564,...,4.72,4.89,4.61,NaN,f,2,2,0,0,0.32
3,24328,https://www.airbnb.com/rooms/24328,20250914034649,2025-09-18,previous scrape,Battersea live/work artist house,"Artist house by SW Battersea Park, bright high...","- Battersea is a quiet family area, easy acces...",https://a0.muscache.com/pictures/9194b40f-c627...,41759,...,4.93,4.60,4.65,NaN,f,1,1,0,0,0.53
4,36274,https://www.airbnb.com/rooms/36274,20250914034649,2025-09-15,city scrape,Bright 1 bedroom apt off brick lane in Shoreditch,*Update June '25- Pump Installed to improve wa...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,133271,...,4.46,4.85,4.54,NaN,t,2,2,0,0,0.09

In [7]:
listings.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='str')

In [8]:
listings.shape

(96871, 79)

The listings dataset contains detailed information about Airbnb listings in London.

Each row represents a single listing and includes information about pricing, location, host details, availability, and review metrics. This dataset serves as the primary table for analysis.

The dataset also includes derived features such as estimated annual revenue and occupancy indicators, which can be leveraged for deeper insights.

In [9]:
listings.isnull().sum().sort_values(ascending=False).head(20)

license                         96871
calendar_updated                96871
neighbourhood_group_cleansed    96871
neighborhood_overview           55663
neighbourhood                   55662
host_neighbourhood              51021
host_about                      47038
beds                            34920
price                           34908
estimated_revenue_l365d         34908
bathrooms                       34846
host_response_rate              31707
host_response_time              31707
host_acceptance_rate            27760
review_scores_location          24166
review_scores_value             24166
review_scores_checkin           24165
review_scores_communication     24142
review_scores_accuracy          24137
review_scores_cleanliness       24131
dtype: int64

## Data Quality Analysis

The dataset contains several missing values across multiple columns.

### Completely Missing or Low-Value Columns
Columns such as `license`, `calendar_updated`, and `neighbourhood_group_cleansed` contain an extremely high proportion of missing values. These fields provide little analytical value and are likely to be removed during the cleaning phase.

### Partially Missing Text Fields
Columns such as `neighborhood_overview` and `host_about` have significant missing values. These fields are descriptive and optional, and while useful for NLP tasks, they are not critical for core analysis.

### Missing Values in Key Numerical Fields
Important variables such as `price`, `beds`, `bathrooms`, and `estimated_revenue_l365d` contain missing values. These will require appropriate handling such as imputation or removal to ensure analytical accuracy.

### Missing Review Metrics
Review-related fields such as `review_scores_location` and `review_scores_cleanliness` are missing for a subset of listings. This is expected as listings without reviews do not have associated scores.

### Host Attributes
Host-related fields such as `host_response_rate` and `host_acceptance_rate` are partially missing, indicating incomplete host-provided data.

Overall, the dataset reflects realistic data imperfections commonly found in scraped datasets, and careful preprocessing will be required before analysis.
These findings will directly inform the data cleaning and preprocessing steps in the next phase of the project.


## Cleaned Dataset Verification

This section verifies that the data cleaning pipeline has been successfully applied and that the dataset is ready for analysis.

In [10]:
cleaned = pd.read_csv("../data/processed/listings_clean.csv")

In [11]:
cleaned.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,13913,https://www.airbnb.com/rooms/13913,20250914034649,2025-09-16,city scrape,Holiday London DB Room Let-on going,My bright double bedroom with a large window h...,Finsbury Park is a friendly melting pot commun...,https://a0.muscache.com/pictures/miso/Hosting-...,54730,...,4.81,4.87,4.78,4.78,f,2,1,1,0,0.30
1,15400,https://www.airbnb.com/rooms/15400,20250914034649,2025-09-16,city scrape,Bright Chelsea Apartment. Chelsea!,Lots of windows and light. St Luke's Gardens ...,It is Chelsea.,https://a0.muscache.com/pictures/428392/462d26...,60302,...,4.88,4.84,4.93,4.74,f,1,1,0,0,0.51
2,17402,https://www.airbnb.com/rooms/17402,20250914034649,2025-09-16,city scrape,Very Central Modern 3-Bed/2 Bath By Oxford St W1,"You'll have a great time in this beautiful, cl...","Fitzrovia is a very desirable trendy, arty and...",https://a0.muscache.com/pictures/39d5309d-fba7...,67564,...,4.72,4.72,4.89,4.61,f,2,2,0,0,0.32
3,24328,https://www.airbnb.com/rooms/24328,20250914034649,2025-09-18,previous scrape,Battersea live/work artist house,"Artist house by SW Battersea Park, bright high...","- Battersea is a quiet family area, easy acces...",https://a0.muscache.com/pictures/9194b40f-c627...,41759,...,4.90,4.93,4.60,4.65,f,1,1,0,0,0.53
4,36274,https://www.airbnb.com/rooms/36274,20250914034649,2025-09-15,city scrape,Bright 1 bedroom apt off brick lane in Shoreditch,*Update June '25- Pump Installed to improve wa...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,133271,...,4.62,4.46,4.85,4.54,t,2,2,0,0,0.09

In [12]:
cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 96871 entries, 0 to 96870
Data columns (total 76 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            96871 non-null  int64
 1   listing_url                                   96871 non-null  str
 2   scrape_id                                     96871 non-null  int64
 3   last_scraped                                  96871 non-null  str
 4   source                                        96871 non-null  str
 5   name                                          96871 non-null  str
 6   description                                   94421 non-null  str
 7   neighborhood_overview                         41208 non-null  str
 8   picture_url                                   96865 non-null  str
 9   host_id                                       96871 non-null  int64
 10  host_url                                      96871 non-null  str
 11  host_name                                     96828 non-null  str
 12  host_since                                    96830 non-null  str
 13  host_location                                 73100 non-null  str
 14  host_about                                    49833 non-null  str
 15  host_response_time                            65164 non-null  str
 16  host_response_rate                            65164 non-null  str
 17  host_acceptance_rate                          69111 non-null  str
 18  host_is_superhost                             95105 non-null  str
 19  host_thumbnail_url                            96830 non-null  str
 20  host_picture_url                              96830 non-null  str
 21  host_neighbourhood                            45850 non-null  str
 22  host_listings_count                           96830 non-null  float64
 23  host_total_listings_count                     96830 non-null  float64
 24  host_verifications                            96830 non-null  str
 25  host_has_profile_pic                          96830 non-null  str
 26  host_identity_verified                        96830 non-null  str
 27  neighbourhood                                 41209 non-null  str
 28  neighbourhood_cleansed                        96871 non-null  str
 29  latitude                                      96871 non-null  float64
 30  longitude                                     96871 non-null  float64
 31  property_type                                 96871 non-null  str
 32  room_type                                     96871 non-null  str
 33  accommodates                                  96871 non-null  int64
 34  bathrooms                                     96871 non-null  float64
 35  bathrooms_text                                96718 non-null  str
 36  bedrooms                                      84096 non-null  float64
 37  beds                                          96871 non-null  float64
 38  amenities                                     96871 non-null  str
 39  price                                         61963 non-null  float64
 40  minimum_nights                                96871 non-null  int64
 41  maximum_nights                                96871 non-null  int64
 42  minimum_minimum_nights                        96868 non-null  float64
 43  maximum_minimum_nights                        96868 non-null  float64
 44  minimum_maximum_nights                        96868 non-null  float64
 45  maximum_maximum_nights                        96868 non-null  float64
 46  minimum_nights_avg_ntm                        96871 non-null  float64
 47  maximum_nights_avg_ntm                        96871 non-null  float64
 48  has_availability                              92622 non-null  str
 49  availability_30                               96871 non-null  int64
 50  availability_60                               96871 non-null  int64
 51  availability_90                               96871 non-null  int64
 52  availability_365                              96871 non-null  int64
 53  calendar_last_scraped                         96871 non-null  str
 54  number_of_reviews                             96871 non-null  int64
 55  number_of_reviews_ltm                         96871 non-null  int64
 56  number_of_reviews_l30d                        96871 non-null  int64
 57  availability_eoy                              96871 non-null  int64
 58  number_of_reviews_ly                          96871 non-null  int64
 59  estimated_occupancy_l365d                     96871 non-null  int64
 60  estimated_revenue_l365d                       61963 non-null  float64
 61  first_review                                  72749 non-null  str
 62  last_review                                   72749 non-null  str
 63  review_scores_rating                          96871 non-null  float64
 64  review_scores_accuracy                        72734 non-null  float64
 65  review_scores_cleanliness                     72740 non-null  float64
 66  review_scores_checkin                         72706 non-null  float64
 67  review_scores_communication                   72729 non-null  float64
 68  review_scores_location                        72705 non-null  float64
 69  review_scores_value                           72705 non-null  float64
 70  instant_bookable                              96871 non-null  str
 71  calculated_host_listings_count                96871 non-null  int64
 72  calculated_host_listings_count_entire_homes   96871 non-null  int64
 73  calculated_host_listings_count_private_rooms  96871 non-null  int64
 74  calculated_host_listings_count_shared_rooms   96871 non-null  int64
 75  reviews_per_month                             72749 non-null  float64
dtypes: float64(23), int64(20), str(33)
memory usage: 56.2 MB

In [13]:
cleaned['price'].dtype

dtype('float64')

In [14]:
cleaned['price'].head()

0     70.0
1    149.0
2    411.0
3      NaN
4    210.0
Name: price, dtype: float64

In [15]:
cleaned.isnull().sum().sort_values(ascending=False).head(10)

neighborhood_overview      55663
neighbourhood              55662
host_neighbourhood         51021
host_about                 47038
price                      34908
estimated_revenue_l365d    34908
host_response_rate         31707
host_response_time         31707
host_acceptance_rate       27760
review_scores_location     24166
dtype: int64

In [16]:
featured = pd.read_csv("../data/processed/listings_featured.csv")

## Feature Engineering

Additional features were created to enhance analytical capabilities:

- Occupancy rate derived from availability
- Estimated annual revenue based on pricing and occupancy
- Price per bedroom for pricing efficiency analysis
- Host tenure to measure host experience

These features enable deeper insights into listing performance and market dynamics.